In [9]:
import pandas as pd
import numpy as np

%matplotlib inline
pd.set_option('display.max_columns',100)

In [10]:
dados = pd.read_csv('2004-2019.tsv',sep='\t')

In [11]:
dados.head()

,Unnamed: 0,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO
0,0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,127,R$/l,1.288,0.016,1.19,1.350,0.463,0.012,0.825,0.11,0.4201,0.9666,0.133,5,2004
1,1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387,R$/l,1.162,0.114,0.89,1.449,0.399,0.098,0.763,0.088,0.5013,1.05,0.115,5,2004
2,2,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,192,R$/l,1.389,0.097,1.18,1.760,0.419,0.070,0.97,0.095,0.5614,1.161,0.098,5,2004
3,3,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,162,R$/l,1.262,0.070,1.09,1.509,0.432,0.055,0.83,0.119,0.5991,1.22242,0.143,5,2004
4,4,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,ETANOL HIDRATADO,103,R$/l,1.181,0.078,1.05,1.400,0.24,0.066,0.941,0.077,0.7441,1.0317,0.082,5,2004

In [6]:
dados['PRODUTO'].value_counts()

GASOLINA COMUM      21194
ÓLEO DIESEL         21194
GLP                 21186
ETANOL HIDRATADO    21102
GNV                 13034
ÓLEO DIESEL S10      9113
Name: PRODUTO, dtype: int64

In [19]:
dt_diesel = dados[dados['PRODUTO'] == 'ÓLEO DIESEL'].copy()

In [20]:
dt_diesel.head()

,Unnamed: 0,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO
43547,43547,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,ÓLEO DIESEL,125,R$/l,1.447,0.031,1.350,1.490,0.198,0.021,1.249,0.012,1.2153,1.2817,0.01,5,2004
43548,43548,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ÓLEO DIESEL,373,R$/l,1.437,0.059,1.300,1.660,0.157,0.041,1.28,0.024,1.2119,1.3801,0.019,5,2004
43549,43549,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,ÓLEO DIESEL,190,R$/l,1.600,0.061,1.460,1.790,0.195,0.038,1.405,0.06,1.22,1.549,0.043,5,2004
43550,43550,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,ÓLEO DIESEL,157,R$/l,1.526,0.045,1.399,1.659,0.163,0.029,1.363,0.022,1.3055,1.4407,0.016,5,2004
43551,43551,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,ÓLEO DIESEL,105,R$/l,1.362,0.025,1.310,1.450,0.146,0.018,1.216,0.02,1.1768,1.272,0.016,5,2004

In [21]:
dt_diesel['DATA FINAL'] = pd.to_datetime(dt_diesel['DATA FINAL'])
dt_diesel['DATA INICIAL'] = pd.to_datetime(dt_diesel['DATA INICIAL'])

In [22]:
dt_diesel.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 21194 entries, 43547 to 106726
Data columns (total 21 columns):
Unnamed: 0                       21194 non-null int64
DATA INICIAL                     21194 non-null datetime64[ns]
DATA FINAL                       21194 non-null datetime64[ns]
REGIÃO                           21194 non-null object
ESTADO                           21194 non-null object
PRODUTO                          21194 non-null object
NÚMERO DE POSTOS PESQUISADOS     21194 non-null int64
UNIDADE DE MEDIDA                21194 non-null object
PREÇO MÉDIO REVENDA              21194 non-null float64
DESVIO PADRÃO REVENDA            21194 non-null float64
PREÇO MÍNIMO REVENDA             21194 non-null float64
PREÇO MÁXIMO REVENDA             21194 non-null float64
MARGEM MÉDIA REVENDA             21194 non-null object
COEF DE VARIAÇÃO REVENDA         21194 non-null float64
PREÇO MÉDIO DISTRIBUIÇÃO         21194 non-null object
DESVIO PADRÃO DISTRIBUIÇÃO       21194 non-null object
PREÇO MÍNIMO DISTRIBUIÇÃO        21194 non-null object
PREÇO MÁXIMO DISTRIBUIÇÃO        21194 non-null object
COEF DE VARIAÇÃO DISTRIBUIÇÃO    21194 non-null object
MÊS                              21194 non-null int64
ANO                              21194 non-null int64
dtypes: datetime64[ns](2), float64(5), int64(4), object(10)
memory usage: 3.6+ MB

In [25]:
(dt_diesel['DATA FINAL'] - dt_diesel['DATA INICIAL']).value_counts()

6 days    21194
dtype: int64

In [29]:
diesel_treino = dt_diesel[dt_diesel['DATA INICIAL'] < '01-01-2011'].copy()
diesel_valid = dt_diesel[dt_diesel['DATA INICIAL'] >= '01-01-2011'].copy()

In [32]:
diesel_treino.shape, diesel_valid.shape

((9260, 21), (11934, 21))

### BASELINE

In [41]:
y_treino = diesel_treino['PREÇO MÉDIO REVENDA']
y_valid = diesel_valid['PREÇO MÉDIO REVENDA']

In [42]:
baseline_treino = diesel_treino.groupby(['ESTADO'])['PREÇO MÉDIO REVENDA'].shift(1)
baseline_valid = diesel_valid.groupby(['ESTADO'])['PREÇO MÉDIO REVENDA'].shift(1)

In [43]:
diesel_treino['baseline'] = baseline_treino

In [44]:
diesel_treino

,Unnamed: 0,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO,baseline
43547,43547,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,ÓLEO DIESEL,125,R$/l,1.447,0.031,1.350,1.490,0.198,0.021,1.249,0.012,1.2153,1.2817,0.01,5,2004,NaN
43548,43548,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ÓLEO DIESEL,373,R$/l,1.437,0.059,1.300,1.660,0.157,0.041,1.28,0.024,1.2119,1.3801,0.019,5,2004,NaN
43549,43549,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,ÓLEO DIESEL,190,R$/l,1.600,0.061,1.460,1.790,0.195,0.038,1.405,0.06,1.22,1.549,0.043,5,2004,NaN
43550,43550,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,ÓLEO DIESEL,157,R$/l,1.526,0.045,1.399,1.659,0.163,0.029,1.363,0.022,1.3055,1.4407,0.016,5,2004,NaN
43551,43551,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,ÓLEO DIESEL,105,R$/l,1.362,0.025,1.310,1.450,0.146,0.018,1.216,0.02,1.1768,1.272,0.016,5,2004,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
52802,52802,2010-12-26,2011-01-01,SUDESTE,RIO DE JANEIRO,ÓLEO DIESEL,574,R$/l,1.983,0.086,1.779,2.280,0.255,0.043,1.728,0.04,1.609,1.8536,0.023,12,2010,1.982
52803,52803,2010-12-26,2011-01-01,SUDESTE,SAO PAULO,ÓLEO DIESEL,1871,R$/l,1.966,0.070,1.699,2.399,0.261,0.036,1.705,0.045,1.5764,1.969,0.026,12,2010,1.963
52804,52804,2010-12-26,2011-01-01,SUL,PARANA,ÓLEO DIESEL,469,R$/l,1.946,0.058,1.799,2.109,0.19,0.030,1.756,0.038,1.659,1.9268,0.022,12,2010,1.953
52805,52805,2010-12-26,2011-01-01,SUL,RIO GRANDE DO SUL,ÓLEO DIESEL,419,R$/l,2.052,0.059,1.890,2.310,0.267,0.029,1.785,0.039,1.677,1.9172,0.022,12,2010,2.051
52806,52806,2010-12-26,2011-01-01,SUL,SANTA CATARINA,ÓLEO DIESEL,328,R$/l,2.018,0.066,1.849,2.210,0.225,0.033,1.793,0.042,1.7,1.8854,0.023,12,2010,2.023

In [47]:
from sklearn.metrics import mean_squared_log_error

erro = np.sqrt(
    mean_squared_log_error(
        y_valid[baseline_valid.notnull()], 
        baseline_valid[baseline_valid.notnull()]
    )
)


erro

0.008142262784282909

In [48]:
erro * 100

0.8142262784282909